# Site settings
title: Ember Responsive
description: > # this means to ignore newlines until "baseurl:"
  Easy responsive layouts with Emberbaseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://github.com" # the base hostname & protocol for your site
baseurl: '/ember-responsive'

# Build settings
markdown: kramdown
